#!/usr/bin/env node
process.chdir(__dirname);
require('../../../nightwatch_master/bin/runner.js');
//require('../../../nightwatch/bin/runner.js');
//require('../../node_modules/nightwatch/bin/runner.js');